//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class StarterSiteEntities : DbContext
{
    public StarterSiteEntities()
        : base("name=StarterSiteEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Average> Averages { get; set; }
    public virtual DbSet<Competition> Competitions { get; set; }
    public virtual DbSet<Document> Documents { get; set; }
    public virtual DbSet<Game> Games { get; set; }
    public virtual DbSet<Score> Scores { get; set; }
    public virtual DbSet<Set> Sets { get; set; }
    public virtual DbSet<UserProfile> UserProfiles { get; set; }
    public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
    public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
    public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
    public virtual DbSet<DocumentStorage> DocumentStorages { get; set; }
}
